INSERT INTO ruleta.jugadores (JUG_NOMBRE,JUG_APELLIDO,JUG_ALIAS) VALUES('Lucas_test','Luquitas','soyLucasBro');
INSERT INTO ruleta.apuestas(JUG_ID,APU_RONDA) VALUES((select jug_id from ruleta.jugadores where jug_nombre='Lucas_test'),2);
--Esta es para eliminar
INSERT INTO ruleta.opcion_grupo(OPG_GRUPO,APU_ID,OPG_SALDO) VALUES(100,(SELECT APU_ID FROM RULETA.APUESTAS WHERE JUG_ID = (SELECT JUG_ID FROM RULETA.JUGADORES WHERE JUG_ALIAS='soyLucasBro')),200);
--esta para modificar
INSERT INTO ruleta.opcion_grupo(OPG_GRUPO,APU_ID,OPG_SALDO) VALUES(400,(SELECT APU_ID FROM RULETA.APUESTAS WHERE JUG_ID = (SELECT JUG_ID FROM RULETA.JUGADORES WHERE JUG_ALIAS='soyLucasBro')),500);
--estas para leer
INSERT INTO ruleta.opcion_grupo(OPG_GRUPO,APU_ID,OPG_SALDO) VALUES(500,(SELECT APU_ID FROM RULETA.APUESTAS WHERE JUG_ID = (SELECT JUG_ID FROM RULETA.JUGADORES WHERE JUG_ALIAS='soyLucasBro')),50);
INSERT INTO ruleta.opcion_grupo(OPG_GRUPO,APU_ID,OPG_SALDO) VALUES(600,(SELECT APU_ID FROM RULETA.APUESTAS WHERE JUG_ID = (SELECT JUG_ID FROM RULETA.JUGADORES WHERE JUG_ALIAS='soyLucasBro')),250);
